name: Kotlin CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dokka:
    name: Assemble & Dokka
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      ## Actual task
      - name: Assemble with gradle — make sure everything builds
        run: ./gradlew assemble --no-daemon --stacktrace

      # This should ideally be done as a Check job below, but it needs to be done as a separate
      # step after running assemble. Heckin' ridikalus.
      # Probably fixed in dokka 1.4.10, but we can't move to kotlin 1.4 yet.
      #  https://github.com/square/workflow/issues/1152.
      - name: Run dokka to validate kdoc
        run: ./gradlew dokka siteDokka --build-cache --no-daemon --stacktrace

  # Runs all check tasks in parallel.
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      # Run all checks, even if some fail.
      fail-fast: false
      matrix:
        gradle-task:
          # Unit tests
          - test
          # Binary compatibility
          - apiCheck
          - lint
          - ktlintCheck
          - detekt
          # Build the JMH benchmarks to verify, but don't run them.
          - jmhJar
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      ## Actual task
      - name: Check with Gradle
        run: ./gradlew ${{ matrix.gradle-task }} --no-daemon --stacktrace

  instrumentation-tests:
    name: Instrumentation tests
    runs-on: macos-latest
    timeout-minutes: 20
    strategy:
      # Allow tests to continue on other devices if they fail on one device.
      fail-fast: false
      matrix:
        api-level:
          # Tests are failing on APIs <24.
          - 24
          - 29
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      ## Actual task
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: ./gradlew connectedCheck --no-daemon --stacktrace

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: insrumentation-test-results
          path: ./**/build/reports/androidTests/connected/**
